import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui-card';
import { Filter, Search } from 'lucide-react';

export const dynamic = 'force-dynamic';

export default async function CRMPipelinePage() {
    // Temporary mock data until actions.ts is rewritten
    const pipeline = [
        { id: '1', name: 'John Doe', contact: '+254700112233', source: 'WhatsApp', stage: 'SALE', lastMessage: 'Great, I will proceed with the payment link.', date: 'Today, 10:45 AM' },
        { id: '2', name: 'Jane Smith', contact: 'jane@example.com', source: 'Website Forms', stage: 'PROSPECTIVE', lastMessage: 'Can you send me the full brochure?', date: 'Today, 09:15 AM' },
        { id: '3', name: 'Unknown', contact: '+254722998877', source: 'WhatsApp', stage: 'CONTACTED', lastMessage: 'Hello, what are your opening hours?', date: 'Yesterday' },
        { id: '4', name: 'Benta Aluoch', contact: 'benta.a@company.co.ke', source: 'Facebook Ads', stage: 'LEAD', lastMessage: '<System: Auto-Responder queued>', date: 'Yesterday' },
    ];

    const getStageColor = (stage: string) => {
        switch (stage) {
            case 'SALE': return 'bg-emerald-100 text-emerald-800 border-[0.5px] border-emerald-300';
            case 'PROSPECTIVE': return 'bg-blue-100 text-blue-800 border-[0.5px] border-blue-300';
            case 'CONTACTED': return 'bg-amber-100 text-amber-800 border-[0.5px] border-amber-300';
            default: return 'bg-slate-100 text-slate-800 border-[0.5px] border-slate-300';
        }
    };

    return (
        <main className="flex min-h-screen flex-col p-8 bg-gray-50">
            <div className="mb-8 flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight text-gray-900">CRM Pipeline</h1>
                    <p className="text-sm text-gray-500 mt-1">Track and manage leads generated by your AI Agents.</p>
                </div>
                <div className="flex gap-2">
                    <button className="flex items-center gap-2 bg-white border border-slate-200 text-slate-700 px-4 py-2 rounded-md font-medium text-sm transition-colors hover:bg-slate-50 shadow-sm">
                        <Filter size={16} /> Filter
                    </button>
                    <div className="relative">
                        <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-slate-400" />
                        <input
                            type="text"
                            placeholder="Search contacts..."
                            className="flex h-10 w-[250px] rounded-md border border-slate-300 bg-white pl-9 pr-3 py-2 text-sm placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-red-600"
                        />
                    </div>
                </div>
            </div>

            <Card className="shadow-sm border-slate-200">
                <CardHeader>
                    <CardTitle>Active Contacts</CardTitle>
                    <CardDescription>All conversations managed by Bazz-Connect and Bazz-Lead.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="relative w-full overflow-auto">
                        <table className="w-full caption-bottom text-sm text-left">
                            <thead className="[&_tr]:border-b border-slate-200">
                                <tr className="transition-colors hover:bg-slate-50/50">
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Date</th>
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Name</th>
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Contact</th>
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Source</th>
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Funnel Stage</th>
                                    <th className="h-12 px-4 align-middle font-medium text-slate-500">Last AI Context</th>
                                </tr>
                            </thead>
                            <tbody className="[&_tr:last-child]:border-0 text-slate-900">
                                {pipeline.map((record) => (
                                    <tr key={record.id} className="border-b transition-colors hover:bg-slate-50">
                                        <td className="p-4 align-middle text-slate-500 text-xs whitespace-nowrap">{record.date}</td>
                                        <td className="p-4 align-middle font-medium">{record.name}</td>
                                        <td className="p-4 align-middle font-mono text-xs">{record.contact}</td>
                                        <td className="p-4 align-middle text-slate-500 text-xs">{record.source}</td>
                                        <td className="p-4 align-middle">
                                            <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-[11px] font-bold tracking-wide uppercase ${getStageColor(record.stage)}`}>
                                                {record.stage}
                                            </span>
                                        </td>
                                        <td className="p-4 align-middle max-w-[300px] truncate text-xs text-slate-600 italic">
                                            "{record.lastMessage}"
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </CardContent>
            </Card>
        </main>
    );
}
